FROM node:carbon-stretch AS builder

WORKDIR /opt/work

COPY . .

RUN npm install

RUN npm run build

FROM node:carbon-alpine

WORKDIR /opt/app

COPY --from=builder /opt/work/dist dist

CMD node dist/server.js
